parameters:
#    apps_site.example.class: Apps\SiteBundle\Example

services:
#    apps_site.example:
#        class: %apps_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
