apps_site_admin:
    resource: "@AppsSiteAdminBundle/Resources/config/routing.yml"
    prefix:   /

apps_site:
    resource: "@AppsSiteBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin